### ISSUE TITLE
Reuse existing RenderPass

### ISSUE THREAD

**Issue by vadixidav** [hasenbanck/egui_wgpu_backend#41]
Currently, this library [creates a new render pass every time execute is called](https://github.com/hasenbanck/egui_wgpu_backend/blob/961125e7bd2c71c5ead1d61a7ca7ffa8c0d17f48/src/lib.rs#L277).

According to the documentation [here](https://developer.arm.com/documentation/102479/0100/Efficient-render-passes), it can incur latency and a round-trip to the GPU when 3d rendering and a 2d UI overlay are not part of the same render pass.

Over at [ennona](https://github.com/rust-cv/ennona), we are currently running a render pass with multiple render pipelines in it to render cameras and points in a point cloud. It would be possible to create only one `wgpu::RenderPass` if we could pass the render pass into `egui_wgpu_backend`. Since it creates a new render pass internally before adding things to that render pass, it should be trivial to create a new method that is passed the render pass to use. For instance, this could be called `execute_with_render_pass`, and then `execute` could call this method.

Does this sound good? I can submit a PR.

**Comment by hasenbanck** [comment]
Hi! I'm not against such an optional method in general, but I think your assumptions are wrong.

As far as I know wgpu, it's re-using render passes when they are compatible (based on the color / depth attachments and the sample count).

When you have a look at the code of the [`begin_render_pass()`](https://github.com/gfx-rs/wgpu/blob/dbf65234a33be0686d1cb4717bb41129420bb796/wgpu-hal/src/vulkan/command.rs#L352) method, you can see that it's creating the rp_key and is then calling the [`make_render_pass()`](https://github.com/gfx-rs/wgpu/blob/dbf65234a33be0686d1cb4717bb41129420bb796/wgpu-hal/src/vulkan/device.rs#L57)  method, which in turn acts as a cache for render passes.

Since I guess that your attachments don't change, it should not create a new render pass at all.

Do you target mobile? The advices you posted above are mainly affecting mobile implementations and the guide also seems to mix advices for OpenGL ES and Vulkan.

**Comment by vadixidav** [comment]
> Hi! I'm not against such an optional method in general, but I think your assumptions are wrong.
> 
> As far as I know wgpu, it's re-using render passes when they are compatible (based on the color / depth attachments and the sample count).
> 
> When you have a look at the code of the [`begin_render_pass()`](https://github.com/gfx-rs/wgpu/blob/dbf65234a33be0686d1cb4717bb41129420bb796/wgpu-hal/src/vulkan/command.rs#L352) method, you can see that it's creating the rp_key and is then calling the [`make_render_pass()`](https://github.com/gfx-rs/wgpu/blob/dbf65234a33be0686d1cb4717bb41129420bb796/wgpu-hal/src/vulkan/device.rs#L57) method, which in turn acts as a cache for render passes.

I see, I wasn't aware that it could actually reuse render passes.

> Do you target mobile? The advices you posted above are mainly affecting mobile implementations and the guide also seems to mix advices for OpenGL ES and Vulkan.

I am still currently learning how a lot of this works, and I was just looking for advice online as to whether there was any impact to having multiple render passes. One of the goals is to eventually be able to target both mobile and web, but that is probably much further off. I think that if it will reuse the same render pass internally, then there should be no issue. I think it was mostly a misunderstanding on my part with how WGPU works.

Thank you for the explanation. It looks like this is a non-issue, so I will go ahead and close this. I might even be able to simplify my code somewhat based on the fact that these render passes are reused. Thanks.
