### ISSUE TITLE
Target wasm

### ISSUE THREAD

**Issue by samsamai** [hasenbanck/egui_wgpu_backend#9]
I was wondering if you had any success with converting egui_wgpu_backend to work for the web?
I'm testing on firefox nightly and getting close (I have been able to get it to draw a test triangle) but feeding in the tessellated data from egui just shows me a black screen which doesn't give much clue about what could be wrong, I've tried many different things without success. :(

**Comment by hasenbanck** [comment]
No, I don't haven any experience with the WebGPU target for firefox nightly and chrome. From what I head it's still _very_ experimential. Since we don't use any native extension of wgpu, it should work under Chrome or Firefox in the future (since they both support SPRIV shader). 

You could try to take a look at the wgpu-rs examples for how to get it run in a browser:
https://github.com/gfx-rs/wgpu-rs/blob/master/examples/framework.rs

What maybe could get problematic is this line:
https://github.com/hasenbanck/egui_wgpu_backend/blob/121cccf6af671eb0e4195d55f18dcc0385f5e16d/src/lib.rs#L76

Maybe the web doesn't support Srgb outputs. I think I heard something about that in the past.

**Comment by samsamai** [comment]
Thanks for the pointers Nils, I will have a into the Srgb output to make sure that is correct. I will close this now as it's not really an issue with egui_wgpu_backend.
